-- CONSOLIDATED SUPABASE SETUP FOR STRESS NO MORE
-- Run this in the Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. Enable UUID Extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Users Table
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  full_name TEXT NOT NULL,
  department TEXT NOT NULL,
  reg_no TEXT UNIQUE,
  is_admin BOOLEAN DEFAULT FALSE,
  has_free_access BOOLEAN DEFAULT FALSE,
  used_free_defense BOOLEAN DEFAULT FALSE,
  balance NUMERIC DEFAULT 0 NOT NULL,
  project_credits INTEGER DEFAULT 0 NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW())
);

-- 3. Projects Table
CREATE TABLE IF NOT EXISTS public.projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  topic TEXT NOT NULL,
  content JSONB NOT NULL,
  details JSONB DEFAULT '{}'::JSONB,
  is_premium_generated BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW())
);

-- 4. Transactions Table
CREATE TABLE IF NOT EXISTS public.transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  amount NUMERIC NOT NULL,
  reference TEXT,
  status TEXT DEFAULT 'successful',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW())
);

-- 5. Top Up Requests Table
CREATE TABLE IF NOT EXISTS public.top_up_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  name TEXT,
  email TEXT,
  transaction_id TEXT,
  amount NUMERIC,
  bank TEXT,
  project_credits INTEGER DEFAULT 0,
  status TEXT DEFAULT 'PENDING',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW())
);

-- 6. Notifications Table
CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT DEFAULT 'system',
  read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW())
);

-- 7. Settings Table
CREATE TABLE IF NOT EXISTS public.settings (
  key TEXT PRIMARY KEY,
  value TEXT
);

-- 8. Messages Table (Support Chat)
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  receiver_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW())
);

-- 9. Pricing Plans Table
CREATE TABLE IF NOT EXISTS public.pricing_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projects_count INTEGER NOT NULL,
    price_naira NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW())
);

-- 10. Indexes for Performance and Anti-Abuse
CREATE INDEX IF NOT EXISTS idx_projects_details_regno ON public.projects ((details->>'regNo'));
CREATE INDEX IF NOT EXISTS idx_projects_details_surname ON public.projects ((details->>'surname'));
CREATE INDEX IF NOT EXISTS idx_users_reg_no ON public.users (reg_no);
CREATE INDEX IF NOT EXISTS idx_projects_user_id ON public.projects(user_id);
CREATE INDEX IF NOT EXISTS idx_projects_created_at ON public.projects(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON public.transactions(user_id);

-- 11. RLS Policies (Permissive for Node Backend)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.top_up_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pricing_plans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all access" ON public.users FOR ALL USING (TRUE) WITH CHECK (TRUE);
CREATE POLICY "Allow all access" ON public.projects FOR ALL USING (TRUE) WITH CHECK (TRUE);
CREATE POLICY "Allow all access" ON public.transactions FOR ALL USING (TRUE) WITH CHECK (TRUE);
CREATE POLICY "Allow all access" ON public.top_up_requests FOR ALL USING (TRUE) WITH CHECK (TRUE);
CREATE POLICY "Allow all access" ON public.notifications FOR ALL USING (TRUE) WITH CHECK (TRUE);
CREATE POLICY "Allow all access" ON public.settings FOR ALL USING (TRUE) WITH CHECK (TRUE);
CREATE POLICY "Allow all access" ON public.messages FOR ALL USING (TRUE) WITH CHECK (TRUE);
CREATE POLICY "Allow all access" ON public.pricing_plans FOR ALL USING (TRUE) WITH CHECK (TRUE);

-- 12. Seed Initial Admin and Settings
INSERT INTO public.users (email, password, full_name, department, reg_no, is_admin, has_free_access)
VALUES ('drexxieofficial@gmail.com', '$2b$10$skdG9o6gKXt1n/4YPrSJ5OlSBdnuP0uNkPq38qXgc3DFza52COYc2', 'Admin', 'Administration', 'ADMIN', TRUE, TRUE)
ON CONFLICT (email) DO NOTHING;

INSERT INTO public.settings (key, value) VALUES ('paymentAmount', '5000') ON CONFLICT (key) DO NOTHING;
INSERT INTO public.settings (key, value) VALUES ('pptPaymentAmount', '5000') ON CONFLICT (key) DO NOTHING;
INSERT INTO public.settings (key, value) VALUES ('project_cost_credits', '1') ON CONFLICT (key) DO NOTHING;
INSERT INTO public.settings (key, value) VALUES ('credit_value_naira', '10000') ON CONFLICT (key) DO NOTHING;
INSERT INTO public.settings (key, value) VALUES ('paymentAccounts', '[{"bankName":"WEMA BANK PLC","accountNumber":"8543944389","accountName":"rtechsse"},{"bankName":"CASHCONNET MICROFINANCE BANK","accountNumber":"9912023600","accountName":"rtechsse"},{"bankName":"STERLING BANK PLC","accountNumber":"8513808366","accountName":"rtechsse"}]') ON CONFLICT (key) DO NOTHING;

-- Seed initial pricing plans
INSERT INTO public.pricing_plans (projects_count, price_naira) VALUES
(1, 10000),
(5, 50000),
(10, 100000),
(15, 150000)
ON CONFLICT DO NOTHING;
