-- 1. Create pricing_plans table
CREATE TABLE IF NOT EXISTS public.pricing_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projects_count INTEGER NOT NULL,
    price_naira NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW())
);

-- 2. Add is_premium_generated to projects table
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS is_premium_generated BOOLEAN DEFAULT FALSE;

-- 3. Insert initial pricing plans
DELETE FROM public.pricing_plans;
INSERT INTO public.pricing_plans (projects_count, price_naira) VALUES
(1, 10000),
(5, 50000),
(10, 100000),
(15, 150000);

-- 4. Update settings for project cost
INSERT INTO public.settings (key, value) VALUES ('project_cost_credits', '1') ON CONFLICT (key) DO UPDATE SET value = '1';
INSERT INTO public.settings (key, value) VALUES ('credit_value_naira', '10000') ON CONFLICT (key) DO UPDATE SET value = '10000';

-- 5. Enable RLS for pricing_plans
ALTER TABLE public.pricing_plans ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all access" ON public.pricing_plans;
CREATE POLICY "Allow all access" ON public.pricing_plans FOR ALL USING (TRUE) WITH CHECK (TRUE);
