-- Enable UUID extension (optional, but good practice)
create extension if not exists "uuid-ossp";

-- Users Table
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text unique not null,
  password text not null,
  full_name text,
  department text,
  reg_no text,
  is_admin boolean default false,
  has_free_access boolean default false,
  balance numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Projects Table
create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  topic text,
  content jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Transactions Table
create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  amount numeric,
  reference text,
  status text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Top Up Requests Table
create table if not exists public.top_up_requests (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  name text,
  email text,
  transaction_id text,
  amount numeric,
  bank text,
  status text default 'PENDING',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Messages Table
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id bigint references public.users(id) on delete cascade,
  receiver_id bigint references public.users(id) on delete cascade,
  content text,
  read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Settings Table
create table if not exists public.settings (
  key text primary key,
  value text
);

-- Notifications Table
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  title text,
  message text,
  type text, -- 'payment', 'announcement', 'system'
  read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- RLS Policies (Row Level Security)
-- Enable RLS on all tables
alter table public.users enable row level security;
alter table public.projects enable row level security;
alter table public.transactions enable row level security;
alter table public.top_up_requests enable row level security;
alter table public.messages enable row level security;
alter table public.settings enable row level security;
alter table public.notifications enable row level security;

-- Policies for Users
-- Users can read their own data
create policy "Users can read own data" on public.users for select using (true); 
-- Note: In a real app with Supabase Auth, you'd use auth.uid() = id. 
-- Since we use custom auth and the backend handles logic, we might need to be permissive for the anon key 
-- IF the backend uses the anon key. 
-- However, the backend should ideally use the SERVICE_ROLE_KEY for admin tasks.
-- Given the current setup uses VITE_SUPABASE_ANON_KEY in the backend, we must allow access.
-- A safer approach for this specific architecture (Node backend + Custom Auth + Supabase as DB only) 
-- is to disable RLS or create permissive policies if we don't switch to Service Role Key.
-- Let's create permissive policies for now to ensure the app works, but warn about it.

create policy "Enable read access for all users" on public.users for select using (true);
create policy "Enable insert access for all users" on public.users for insert with check (true);
create policy "Enable update access for all users" on public.users for update using (true);

-- Policies for Projects
create policy "Enable read access for all projects" on public.projects for select using (true);
create policy "Enable insert access for all projects" on public.projects for insert with check (true);
create policy "Enable update access for all projects" on public.projects for update using (true);
create policy "Enable delete access for all projects" on public.projects for delete using (true);

-- Policies for Transactions
create policy "Enable all access for transactions" on public.transactions for all using (true);

-- Policies for Top Up Requests
create policy "Enable all access for top_up_requests" on public.top_up_requests for all using (true);

-- Policies for Messages
create policy "Enable all access for messages" on public.messages for all using (true);

-- Policies for Settings
create policy "Enable all access for settings" on public.settings for all using (true);

-- Policies for Notifications
create policy "Enable all access for notifications" on public.notifications for all using (true);


-- Seed Admin User (Password: 311868)
-- Note: In a real app, use Supabase Auth. This is for compatibility with existing custom auth.
-- The password hash here is a placeholder. The app will need to handle hashing.
insert into public.users (email, password, full_name, department, reg_no, is_admin, has_free_access)
values ('drexxieofficial@gmail.com', '$2b$10$skdG9o6gKXt1n/4YPrSJ5OlSBdnuP0uNkPq38qXgc3DFza52COYc2', 'Admin', 'Administration', 'ADMIN', true, true)
on conflict (email) do update set password = excluded.password;

-- Seed Settings
insert into public.settings (key, value)
values ('paymentAmount', '5000')
on conflict (key) do nothing;

insert into public.settings (key, value)
values ('pptPaymentAmount', '5000')
on conflict (key) do nothing;

-- Seed Payment Accounts
insert into public.settings (key, value)
values ('paymentAccounts', '[{"bankName":"WEMA BANK PLC","accountNumber":"8543944389","accountName":"rtechsse"},{"bankName":"CASHCONNET MICROFINANCE BANK","accountNumber":"9912023600","accountName":"rtechsse"},{"bankName":"STERLING BANK PLC","accountNumber":"8513808366","accountName":"rtechsse"}]')
on conflict (key) do nothing;
