import { useState, useContext } from 'react';
import { motion } from 'motion/react';
import { ArrowLeft, Save, Edit3, FileText, Download, Check, Presentation, Loader2, X, ShieldAlert, BookOpen, Settings } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { UserContext } from '../App';
import pptxgen from 'pptxgenjs';
import { clientFetch } from '../utils/api';
import PremiumModal from './PremiumModal';
import CitationManager from './CitationManager';
import { generateProjectPDF } from '../utils/pdfGenerator';
import { checkPlagiarism } from '../utils/gemini';
import { PdfOptions, Citation } from '../types';

interface ProjectEditorProps {
  key?: string;
  project: any;
  onBack: () => void;
  onSave: (updatedProject: any) => void;
  onNavigate: (step: any) => void;
}

export default function ProjectEditor({ project, onBack, onSave, onNavigate }: ProjectEditorProps) {
  const { user, setUser } = useContext(UserContext);
  const [content, setContent] = useState<any>(project.content || {});
  const [topic, setTopic] = useState(project.topic || '');
  const [details, setDetails] = useState<any>(project.details || {});
  const [activeTab, setActiveTab] = useState<string>('chapter1');
  const [isEditing, setIsEditing] = useState(true);
  const [isGeneratingPpt, setIsGeneratingPpt] = useState(false);
  const [showPptModal, setShowPptModal] = useState(false);
  const [pptPaymentAmount, setPptPaymentAmount] = useState(5000);
  
  // Premium Modal State
  const [showPremiumModal, setShowPremiumModal] = useState(false);
  const [premiumFeatureName, setPremiumFeatureName] = useState('');

  // Plagiarism State
  const [isCheckingPlagiarism, setIsCheckingPlagiarism] = useState(false);
  const [plagiarismResult, setPlagiarismResult] = useState<{ score: number; report: string } | null>(null);

  // Citation State
  const [showCitationManager, setShowCitationManager] = useState(false);

  // PDF Options State
  const [showPdfSettings, setShowPdfSettings] = useState(false);
  const [pdfOptions, setPdfOptions] = useState<PdfOptions>({
    fontFamily: 'times',
    fontSize: 12,
    lineSpacing: 1.5,
    showPageNumbers: true,
    pageNumberPosition: 'top-right'
  });

  const tabs = [
    { id: 'abstract', label: 'Abstract' },
    { id: 'chapter1', label: 'Chapter 1' },
    { id: 'chapter2', label: 'Chapter 2' },
    { id: 'chapter3', label: 'Chapter 3' },
    { id: 'chapter4', label: 'Chapter 4' },
    { id: 'chapter5', label: 'Chapter 5' },
    { id: 'references', label: 'References' },
    { id: 'dedication', label: 'Dedication' },
    { id: 'acknowledgement', label: 'Acknowledgement' },
    { id: 'details', label: 'Project Details' },
  ];

  const handleSave = () => {
    onSave({ ...project, topic, content, details });
  };

  const handleCheckPlagiarism = async () => {
    if (!user?.hasFreeAccess) {
      setPremiumFeatureName('Plagiarism Checker');
      setShowPremiumModal(true);
      return;
    }

    setIsCheckingPlagiarism(true);
    try {
      const textToCheck = content[activeTab] || '';
      if (textToCheck.length < 100) {
        alert('Text is too short for a meaningful plagiarism check.');
        return;
      }
      const result = await checkPlagiarism(textToCheck);
      setPlagiarismResult(result);
    } catch (error) {
      console.error('Plagiarism check error:', error);
      alert('Failed to check plagiarism. Please try again.');
    } finally {
      setIsCheckingPlagiarism(false);
    }
  };

  const handleGeneratePdf = () => {
    if (!user?.hasFreeAccess) {
      setPremiumFeatureName('PDF Download');
      setShowPremiumModal(true);
      return;
    }

    generateProjectPDF(details, content, true, pdfOptions);
  };

  const generatePpt = () => {
    const pres = new pptxgen();
    
    // Define Master Slide
    pres.defineSlideMaster({
      title: "MASTER_SLIDE",
      background: { color: "FFFFFF" },
      objects: [
        { rect: { x: 0, y: 0, w: "100%", h: 0.6, fill: { color: "008060" } } },
        { text: { text: topic, options: { x: 0.2, y: 0.1, w: "90%", h: 0.4, fontSize: 12, color: "FFFFFF", bold: true } } },
        { text: { text: "Generated by Stress No More", options: { x: 0.2, y: 5.3, w: "90%", h: 0.3, fontSize: 10, color: "888888", align: "right" } } }
      ]
    });

    // Title Slide
    let slide = pres.addSlide();
    slide.addText(topic.toUpperCase(), { 
      x: 1, y: 1.5, w: '80%', h: 1.5, 
      fontSize: 32, bold: true, align: 'center', 
      color: '008060'
    });
    const fullName = `${details.surname || ''} ${details.firstName || ''}`.trim() || user?.fullName || 'Student';
    slide.addText(`BY\n${fullName}`, { 
      x: 1, y: 3.2, w: '80%', 
      fontSize: 20, align: 'center', 
      color: '363636' 
    });
    slide.addText(`DEPARTMENT OF ${details.department?.toUpperCase() || user?.department?.toUpperCase() || 'EDUCATION'}`, { 
      x: 1, y: 4.8, w: '80%', 
      fontSize: 16, align: 'center', 
      color: '666666' 
    });

    // Abstract
    slide = pres.addSlide({ masterName: "MASTER_SLIDE" });
    slide.addText("ABSTRACT", { x: 0.5, y: 0.8, fontSize: 24, bold: true, color: '008060' });
    slide.addText(content.abstract || "No abstract provided.", { 
      x: 0.5, y: 1.5, w: '90%', h: 3.5, 
      fontSize: 14, align: 'justify', 
      valign: 'top' 
    });

    // Chapters
    const chapterList = [
      { title: "Chapter 1: Introduction", text: content.chapter1 },
      { title: "Chapter 2: Literature Review", text: content.chapter2 },
      { title: "Chapter 3: Methods", text: content.chapter3 },
      { title: "Chapter 4: Results", text: content.chapter4 },
      { title: "Chapter 5: Conclusion & Recommendations", text: content.chapter5 },
    ];

    chapterList.forEach(ch => {
      const maxLength = 1500;
      const text = ch.text || "No content generated for this chapter.";
      const chunks = [];
      for (let i = 0; i < text.length; i += maxLength) {
        chunks.push(text.substring(i, i + maxLength));
      }

      chunks.forEach((chunk, idx) => {
        slide = pres.addSlide({ masterName: "MASTER_SLIDE" });
        slide.addText(idx === 0 ? ch.title : `${ch.title} (Continued)`, { 
          x: 0.5, y: 0.8, fontSize: 24, bold: true, color: '008060' 
        });
        slide.addText(chunk, { 
          x: 0.5, y: 1.5, w: '90%', h: 3.5, 
          fontSize: 13, align: 'justify', 
          valign: 'top' 
        });
      });
    });

    pres.writeFile({ fileName: `${topic.substring(0, 30)}_Presentation.pptx` });
  };

  const handlePptPaymentAndGeneration = async () => {
    const hasCredits = (user?.project_credits || 0) > 0;
    const cost = hasCredits ? 1000 : 5000;

    if ((user?.balance || 0) < cost) {
      alert('Insufficient balance. Please top up your wallet.');
      return;
    }

    setIsGeneratingPpt(true);
    try {
      const res = await clientFetch('/api/projects/ppt-deduct', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          topic
        })
      });

      const data = await res.json();

      if (data.success) {
        setUser({ ...user, balance: data.balance, project_credits: data.credits });
        generatePpt();
        setShowPptModal(false);
      } else {
        alert(data.error || 'Payment failed. Please try again.');
      }
    } catch (error) {
      console.error('PPT generation error:', error);
      alert('An error occurred. Please try again.');
    } finally {
      setIsGeneratingPpt(false);
    }
  };

  const handleContentChange = (value: string) => {
    setContent({ ...content, [activeTab]: value });
  };

  const handleDetailChange = (key: string, value: string) => {
    setDetails({ ...details, [key]: value });
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="min-h-screen p-4 md:p-8 max-w-full mx-auto pb-24 relative bg-slate-50 dark:bg-slate-950 flex flex-col"
    >
      <div className="flex flex-col sm:flex-row justify-between items-stretch sm:items-center mb-4 md:mb-6 gap-3 md:gap-4">
        <button 
          onClick={onBack}
          className="flex items-center justify-center text-slate-500 dark:text-slate-400 hover:text-emerald-600 transition-colors bg-white dark:bg-slate-900 px-3 py-2 rounded-xl shadow-sm border border-slate-200 dark:border-slate-800 text-xs font-medium"
        >
          <ArrowLeft className="w-3.5 h-3.5 mr-1.5" />
          Back
        </button>
        <div className="grid grid-cols-2 md:flex items-center gap-2">
          <button 
            onClick={() => setShowCitationManager(true)}
            className="flex items-center justify-center bg-emerald-100 dark:bg-emerald-900/20 text-emerald-700 dark:text-emerald-400 px-2 py-2 rounded-lg hover:bg-emerald-200 dark:hover:bg-emerald-900/30 transition-all font-bold text-[10px]"
          >
            <BookOpen className="w-3 h-3 mr-1" />
            Citations
          </button>
          <button 
            onClick={handleCheckPlagiarism}
            disabled={isCheckingPlagiarism}
            className="flex items-center justify-center bg-red-100 dark:bg-red-900/20 text-red-700 dark:text-red-400 px-2 py-2 rounded-lg hover:bg-red-200 dark:hover:bg-red-900/30 transition-all font-bold text-[10px] disabled:opacity-50"
          >
            {isCheckingPlagiarism ? <Loader2 className="w-3 h-3 animate-spin mr-1" /> : <ShieldAlert className="w-3 h-3 mr-1" />}
            Plagiarism
          </button>
          <button 
            onClick={() => setShowPdfSettings(true)}
            className="flex items-center justify-center bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 px-2 py-2 rounded-lg hover:bg-slate-200 dark:hover:bg-slate-700 transition-all font-bold text-[10px]"
          >
            <Settings className="w-3 h-3 mr-1" />
            PDF
          </button>
          <button 
            onClick={() => setShowPptModal(true)}
            className="flex items-center justify-center bg-orange-100 dark:bg-orange-900/20 text-orange-700 dark:text-orange-400 px-2 py-2 rounded-lg hover:bg-orange-200 dark:hover:bg-orange-900/30 transition-all font-bold text-[10px]"
          >
            <Presentation className="w-3 h-3 mr-1" />
            PPT
          </button>
          <button 
            onClick={() => onNavigate('review')}
            className="flex items-center justify-center bg-purple-100 dark:bg-purple-900/20 text-purple-700 dark:text-purple-400 px-2 py-2 rounded-lg hover:bg-purple-200 dark:hover:bg-purple-900/30 transition-all font-bold text-[10px]"
          >
            <FileText className="w-3 h-3 mr-1" />
            Preview
          </button>
          <button 
            onClick={handleGeneratePdf}
            className="flex items-center justify-center bg-blue-100 dark:bg-blue-900/20 text-blue-700 dark:text-blue-400 px-2 py-2 rounded-lg hover:bg-blue-200 dark:hover:bg-blue-900/30 transition-all font-bold text-[10px]"
          >
            <Download className="w-3 h-3 mr-1" />
            PDF
          </button>
          <button 
            onClick={handleSave}
            className="col-span-2 md:flex-none flex items-center justify-center bg-emerald-600 text-white px-4 py-2 rounded-lg hover:bg-emerald-700 transition-all shadow-lg shadow-emerald-600/20 font-bold text-xs"
          >
            <Save className="w-3.5 h-3.5 mr-1.5" />
            Save
          </button>
        </div>
      </div>

      {/* Premium Modal */}
      <PremiumModal
        isOpen={showPremiumModal}
        onClose={() => setShowPremiumModal(false)}
        onSubscribe={() => {
          setShowPremiumModal(false);
          onNavigate('topup');
        }}
        featureName={premiumFeatureName}
      />

      {/* Citation Manager */}
      {showCitationManager && (
        <CitationManager 
          citations={content.citations || []}
          onUpdate={(citations) => setContent({ ...content, citations })}
          onClose={() => setShowCitationManager(false)}
        />
      )}

      {/* Plagiarism Result Modal */}
      {plagiarismResult && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4 backdrop-blur-sm">
          <motion.div 
            initial={{ scale: 0.9, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            className="bg-white dark:bg-slate-900 rounded-2xl p-6 w-full max-w-md shadow-xl border border-slate-100 dark:border-slate-800"
          >
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-bold text-slate-900 dark:text-white flex items-center">
                <ShieldAlert className="w-5 h-5 mr-2 text-red-500" />
                Originality Report
              </h3>
              <button onClick={() => setPlagiarismResult(null)} className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-200">
                <X className="w-5 h-5" />
              </button>
            </div>
            
            <div className="space-y-4">
              <div className="flex items-center justify-between p-4 bg-slate-50 dark:bg-slate-800 rounded-xl">
                <span className="text-sm font-medium text-slate-600 dark:text-slate-400">Plagiarism Score</span>
                <span className={`text-2xl font-bold ${plagiarismResult.score < 15 ? 'text-emerald-500' : plagiarismResult.score < 30 ? 'text-orange-500' : 'text-red-500'}`}>
                  {plagiarismResult.score}%
                </span>
              </div>
              
              <div className="p-4 border border-slate-100 dark:border-slate-800 rounded-xl">
                <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
                  {plagiarismResult.report}
                </p>
              </div>

              <button 
                onClick={() => setPlagiarismResult(null)}
                className="w-full bg-slate-900 dark:bg-slate-100 text-white dark:text-slate-900 py-3 rounded-xl font-bold hover:opacity-90 transition-all"
              >
                Close Report
              </button>
            </div>
          </motion.div>
        </div>
      )}

      {/* PDF Settings Modal */}
      {showPdfSettings && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4 backdrop-blur-sm">
          <motion.div 
            initial={{ scale: 0.9, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            className="bg-white dark:bg-slate-900 rounded-2xl p-6 w-full max-w-md shadow-xl border border-slate-100 dark:border-slate-800"
          >
            <div className="flex justify-between items-center mb-6">
              <h3 className="text-lg font-bold text-slate-900 dark:text-white flex items-center">
                <Settings className="w-5 h-5 mr-2 text-emerald-500" />
                PDF Customization
              </h3>
              <button onClick={() => setShowPdfSettings(false)} className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-200">
                <X className="w-5 h-5" />
              </button>
            </div>
            
            <div className="space-y-6">
              <div className="space-y-2">
                <label className="text-xs font-bold text-slate-500 uppercase">Font Family</label>
                <select 
                  value={pdfOptions.fontFamily}
                  onChange={e => setPdfOptions({...pdfOptions, fontFamily: e.target.value as any})}
                  className="w-full p-3 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-slate-900 dark:text-white"
                >
                  <option value="times">Times New Roman (Standard)</option>
                  <option value="helvetica">Helvetica (Modern)</option>
                  <option value="courier">Courier (Typewriter)</option>
                </select>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <label className="text-xs font-bold text-slate-500 uppercase">Font Size</label>
                  <input 
                    type="number" 
                    value={pdfOptions.fontSize}
                    onChange={e => setPdfOptions({...pdfOptions, fontSize: parseInt(e.target.value)})}
                    className="w-full p-3 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-slate-900 dark:text-white"
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-xs font-bold text-slate-500 uppercase">Line Spacing</label>
                  <input 
                    type="number" 
                    step="0.1"
                    value={pdfOptions.lineSpacing}
                    onChange={e => setPdfOptions({...pdfOptions, lineSpacing: parseFloat(e.target.value)})}
                    className="w-full p-3 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-slate-900 dark:text-white"
                  />
                </div>
              </div>

              <div className="space-y-2">
                <label className="text-xs font-bold text-slate-500 uppercase">Page Number Position</label>
                <select 
                  value={pdfOptions.pageNumberPosition}
                  onChange={e => setPdfOptions({...pdfOptions, pageNumberPosition: e.target.value as any})}
                  className="w-full p-3 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-slate-900 dark:text-white"
                >
                  <option value="top-right">Top Right</option>
                  <option value="bottom-center">Bottom Center</option>
                  <option value="bottom-right">Bottom Right</option>
                </select>
              </div>

              <div className="flex items-center justify-between p-3 bg-slate-50 dark:bg-slate-800 rounded-xl">
                <span className="text-sm font-medium text-slate-700 dark:text-slate-300">Show Page Numbers</span>
                <button 
                  onClick={() => setPdfOptions({...pdfOptions, showPageNumbers: !pdfOptions.showPageNumbers})}
                  className={`w-12 h-6 rounded-full transition-colors relative ${pdfOptions.showPageNumbers ? 'bg-emerald-500' : 'bg-slate-300 dark:bg-slate-700'}`}
                >
                  <div className={`absolute top-1 w-4 h-4 bg-white rounded-full transition-all ${pdfOptions.showPageNumbers ? 'left-7' : 'left-1'}`} />
                </button>
              </div>

              <button 
                onClick={() => setShowPdfSettings(false)}
                className="w-full bg-emerald-600 text-white py-3 rounded-xl font-bold hover:bg-emerald-700 transition-all"
              >
                Apply Settings
              </button>
            </div>
          </motion.div>
        </div>
      )}

      {/* PPT Modal */}
      {showPptModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4 backdrop-blur-sm">
          <motion.div 
            initial={{ scale: 0.9, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            className="bg-white dark:bg-slate-900 rounded-2xl p-6 w-full max-w-sm shadow-xl border border-slate-100 dark:border-slate-800"
          >
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-bold text-slate-900 dark:text-white">Generate Presentation</h3>
              <button onClick={() => setShowPptModal(false)} className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-200">
                <X className="w-5 h-5" />
              </button>
            </div>
            
            <div className="space-y-4">
              <p className="text-sm text-slate-600 dark:text-slate-400">You are about to generate a PowerPoint presentation for your project: <span className="font-bold text-slate-800 dark:text-slate-200">{topic}</span></p>
              
              <div className="text-center p-4 bg-emerald-50 dark:bg-emerald-900/20 rounded-xl">
                <p className="text-sm text-emerald-800 dark:text-emerald-300">Cost</p>
                <p className="text-3xl font-bold text-emerald-900 dark:text-emerald-200">
                  {(user?.project_credits || 0) > 0 ? '1 Credit + ₦1,000' : '₦5,000'}
                </p>
              </div>
              
              <button 
                onClick={handlePptPaymentAndGeneration}
                disabled={isGeneratingPpt}
                className="w-full bg-emerald-600 text-white py-3 rounded-xl font-bold hover:bg-emerald-700 transition-colors flex items-center justify-center disabled:opacity-50"
              >
                {isGeneratingPpt ? (
                  <>
                    <Loader2 className="w-5 h-5 animate-spin mr-2" />
                    Generating...
                  </>
                ) : 'Pay & Generate'}
              </button>
            </div>
          </motion.div>
        </div>
      )}

      <div className="mb-6 bg-white dark:bg-slate-900 p-6 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-800">
        <label className="block text-sm font-medium text-slate-500 mb-2">Project Topic</label>
        <input
          type="text"
          value={topic}
          onChange={(e) => setTopic(e.target.value)}
          className="w-full text-xl md:text-2xl font-bold text-slate-900 dark:text-white bg-transparent border-none focus:ring-0 outline-none p-0"
          placeholder="Enter project topic..."
        />
      </div>

      <div className="flex flex-1 gap-6 overflow-hidden flex-col lg:flex-row">
        {/* Sidebar */}
        <div className="w-full lg:w-64 flex-shrink-0 bg-white dark:bg-slate-900 rounded-xl shadow-sm border border-slate-200 dark:border-slate-800 overflow-y-auto max-h-[200px] lg:max-h-full">
          <div className="p-4 border-b border-slate-100 dark:border-slate-800 font-semibold text-slate-700 dark:text-slate-200 flex items-center">
            <FileText className="w-4 h-4 mr-2 text-emerald-600" />
            Chapters
          </div>
          <div className="p-2 space-y-1">
            {tabs.map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`w-full text-left px-4 py-3 rounded-lg text-sm font-medium transition-colors ${
                  activeTab === tab.id 
                    ? 'bg-emerald-50 dark:bg-emerald-900/20 text-emerald-700 dark:text-emerald-400' 
                    : 'text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800'
                }`}
              >
                {tab.label}
              </button>
            ))}
          </div>
        </div>

        {/* Editor Area */}
        <div className="flex-1 bg-white dark:bg-slate-900 rounded-xl shadow-sm border border-slate-200 dark:border-slate-800 flex flex-col overflow-hidden">
          <div className="p-4 border-b border-slate-100 dark:border-slate-800 flex justify-between items-center bg-slate-50/50 dark:bg-slate-800/50">
            <h3 className="font-semibold text-slate-800 dark:text-slate-100">
              {tabs.find(t => t.id === activeTab)?.label}
            </h3>
            <div className="flex items-center gap-4">
              <button 
                onClick={() => setIsEditing(!isEditing)}
                className="flex items-center text-sm text-emerald-600 dark:text-emerald-400 hover:text-emerald-700 font-medium"
              >
                <Edit3 className="w-4 h-4 mr-1" />
                {isEditing ? 'Preview' : 'Edit'}
              </button>
            </div>
          </div>

          <div className="flex-1 overflow-hidden">
            {activeTab === 'details' ? (
              <div className="h-full overflow-y-auto p-6 md:p-8 space-y-4">
                <div className="grid md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Surname</label>
                    <input type="text" value={details.surname || ''} onChange={e => handleDetailChange('surname', e.target.value)} className="w-full p-3 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-slate-900 dark:text-white" />
                  </div>
                  <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase mb-1">First Name</label>
                    <input type="text" value={details.firstName || ''} onChange={e => handleDetailChange('firstName', e.target.value)} className="w-full p-3 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-slate-900 dark:text-white" />
                  </div>
                  <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Reg No</label>
                    <input type="text" value={details.regNo || ''} onChange={e => handleDetailChange('regNo', e.target.value)} className="w-full p-3 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-slate-900 dark:text-white" />
                  </div>
                  <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Department</label>
                    <input type="text" value={details.department || ''} onChange={e => handleDetailChange('department', e.target.value)} className="w-full p-3 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-slate-900 dark:text-white" />
                  </div>
                  <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Supervisor</label>
                    <input type="text" value={details.supervisorName || ''} onChange={e => handleDetailChange('supervisorName', e.target.value)} className="w-full p-3 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-slate-900 dark:text-white" />
                  </div>
                  <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase mb-1">HOD</label>
                    <input type="text" value={details.headOfDepartment || ''} onChange={e => handleDetailChange('headOfDepartment', e.target.value)} className="w-full p-3 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-slate-900 dark:text-white" />
                  </div>
                  <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Dean</label>
                    <input type="text" value={details.deanOfFaculty || ''} onChange={e => handleDetailChange('deanOfFaculty', e.target.value)} className="w-full p-3 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-slate-900 dark:text-white" />
                  </div>
                  <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Date</label>
                    <input type="text" value={details.date || ''} onChange={e => handleDetailChange('date', e.target.value)} className="w-full p-3 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-slate-900 dark:text-white" />
                  </div>
                </div>
              </div>
            ) : isEditing ? (
              <textarea
                value={content[activeTab] || ''}
                onChange={(e) => handleContentChange(e.target.value)}
                className="w-full h-full p-6 md:p-8 border-none font-mono text-sm md:text-base bg-transparent text-slate-900 dark:text-white outline-none resize-none leading-relaxed"
                placeholder={`Write ${tabs.find(t => t.id === activeTab)?.label} here...`}
              />
            ) : (
              <div className="h-full overflow-y-auto p-8 md:p-12 prose dark:prose-invert prose-slate max-w-none">
                <ReactMarkdown>{String(content[activeTab] || '*No content yet.*')}</ReactMarkdown>
              </div>
            )}
          </div>
        </div>
      </div>
    </motion.div>
  );
}
